name: number_aacharya
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.3.2
  path_provider: ^2.0.1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdfviewer: ^30.2.7
  cached_network_image: ^3.3.0
  permission_handler: ^12.0.1
  dio: ^5.9.0
  intl: ^0.20.2
  video_player: ^2.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   
    - assets/images/splash.png
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/login.png
    - assets/images/search.png
    - assets/images/analyzing.png
    - assets/images/main.png
    - assets/images/profile.png
    - assets/icons/Joyent.png
    - assets/icons/download.png
    - assets/icons/Export Pdf.png
    - assets/icons/Home.png
    - assets/icons/notification.png
    - assets/icons/Opened Folder.png
    - assets/icons/Settings.png
    - assets/icons/Tags.png
    - assets/icons/credit1.png
    - assets/icons/credit5.png
    - assets/icons/credit10.png
    - assets/icons/credit20.png
    - assets/icons/maincredit.png
    - assets/images/report_screen.png
    - assets/images/conductor.jpg
    - assets/images/driver_number.jpg
    - assets/icons/view.jpg
    - assets/images/enter_details.png
    - assets/images/bg.png
    - assets/images/Fristname.png
    - assets/images/lastname.png
    - assets/images/dob.png
    - assets/images/phoneno.png
    - assets/images/splash.mp4
    - assets/images/report.png
    - assets/images/AMIG.png
    - assets/images/intro3.png
    - assets/images/intro4.png
    - assets/images/banner.png

